name: Code Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run bandit
        run: |
          poetry run bandit -f txt -o code_scanners_examples/bandit_report.txt bandit_report.py 
        continue-on-error: true

      - name: Run radon
        run: |
          poetry run radon cc code_scanners_examples/bad_complexity.py --json > radon_report.json
        continue-on-error: true

      - name: Export Requirements
        run: |
          poetry export --format requirements.txt --output requirements.txt

      - name: Run safety
        run: |
          poetry run safety check -r requirements.txt --json > safety_report.json
        continue-on-error: true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-reports
          path: |
            bandit_report.txt
            radon_report.json
            safety_report.json
